services:
  - type: web
    name: ai-resume-pro
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn resume_builder.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "ai-resume-pro.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://ai-resume-pro.onrender.com"
